name: Pip compile and upgrade
on: 
  pull_request:
    branches:
      - main
jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    env:
      AuthorEmail: ${{ github.event.pull_request.user.email }}
      AuthorName: ${{ github.event.pull_request.user.name }}
    steps:
      - name: Checkout infrastructure
        uses: actions/checkout@v4
          
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"  
      
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Upgrade dependencies and compile requirements file
        run: |
          pip-compile --output-file=requirements.txt pyproject.toml --upgrade
      
      - name: Checkout and commit
        run: |
          git config --global user.name "GitHub Actions (${AuthorName})"
          git config --global user.email ${AuthorEmail}
          git add requirements.txt
          git commit --message "GHA: Upgrade dependencies in requirements.txt"
          git push
