name: Pip compile and upgrade
on: 
  pull_request:
    branches:
      - main
jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/tags/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout infrastructure
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.deploy_key }}
          ref: ${{ steps.extract_branch.outputs.branch }}
            
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"  
      
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Upgrade dependencies and compile requirements file
        run: |
          pip-compile --output-file=requirements.txt pyproject.toml --upgrade
      
      - name: Checkout and commit
        run: |
          git config --global user.name "${{github.actor}}"
          git config --global user.email ""
          git add requirements.txt
          git commit --message "GHA: Upgrade dependencies in requirements.txt"
          git push 
